//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DoosanTeleop
{
    [Serializable]
    public class TeleopStatusMsg : Message
    {
        public const string k_RosMessageName = "doosan_teleop_msgs/TeleopStatus";
        public override string RosMessageName => k_RosMessageName;

        //  TeleopStatus.msg
        //  Published by doosan_vr_teleop on /teleop/status
        //  Gives the Unity app a single topic to monitor the full system state
        public Std.HeaderMsg header;
        public bool vr_connected;
        //  Unity app is publishing controller data
        public bool teleop_active;
        //  Bridge is streaming commands to Servo
        public bool servo_ready;
        //  MoveIt Servo has been activated
        public byte servo_status;
        //  Raw MoveIt Servo status code (0-6)
        //  Servo status codes:
        //    0 = INVALID
        //    1 = NO_WARNING
        //    2 = DECELERATE_SINGULARITY
        //    3 = HALT_SINGULARITY
        //    4 = DECELERATE_COLLISION
        //    5 = HALT_COLLISION
        //    6 = JOINT_BOUND
        public string status_message;
        //  Human-readable status string

        public TeleopStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.vr_connected = false;
            this.teleop_active = false;
            this.servo_ready = false;
            this.servo_status = 0;
            this.status_message = "";
        }

        public TeleopStatusMsg(Std.HeaderMsg header, bool vr_connected, bool teleop_active, bool servo_ready, byte servo_status, string status_message)
        {
            this.header = header;
            this.vr_connected = vr_connected;
            this.teleop_active = teleop_active;
            this.servo_ready = servo_ready;
            this.servo_status = servo_status;
            this.status_message = status_message;
        }

        public static TeleopStatusMsg Deserialize(MessageDeserializer deserializer) => new TeleopStatusMsg(deserializer);

        private TeleopStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.vr_connected);
            deserializer.Read(out this.teleop_active);
            deserializer.Read(out this.servo_ready);
            deserializer.Read(out this.servo_status);
            deserializer.Read(out this.status_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.vr_connected);
            serializer.Write(this.teleop_active);
            serializer.Write(this.servo_ready);
            serializer.Write(this.servo_status);
            serializer.Write(this.status_message);
        }

        public override string ToString()
        {
            return "TeleopStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nvr_connected: " + vr_connected.ToString() +
            "\nteleop_active: " + teleop_active.ToString() +
            "\nservo_ready: " + servo_ready.ToString() +
            "\nservo_status: " + servo_status.ToString() +
            "\nstatus_message: " + status_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
