//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DoosanTeleop
{
    [Serializable]
    public class VRControllerInputMsg : Message
    {
        public const string k_RosMessageName = "doosan_teleop_msgs/VRControllerInput";
        public override string RosMessageName => k_RosMessageName;

        //  VRControllerInput.msg
        //  Published by the Unity VR app on /vr/right/inputs and /vr/left/inputs
        //  Carries the full state of one Meta Quest 2 controller
        public bool button_lower;
        //  Lower trigger button (pause / anchor-reset)
        public bool button_upper;
        //  Upper face button (A on right, X on left)
        public float trigger_index;
        //  Index trigger pressure  (0.0 - 1.0)
        public float trigger_middle;
        //  Middle trigger pressure (0.0 - 1.0)
        public float thumbstick_x;
        //  Horizontal thumbstick  (-1.0 - 1.0)
        public float thumbstick_y;
        //  Vertical thumbstick    (-1.0 - 1.0)

        public VRControllerInputMsg()
        {
            this.button_lower = false;
            this.button_upper = false;
            this.trigger_index = 0.0f;
            this.trigger_middle = 0.0f;
            this.thumbstick_x = 0.0f;
            this.thumbstick_y = 0.0f;
        }

        public VRControllerInputMsg(bool button_lower, bool button_upper, float trigger_index, float trigger_middle, float thumbstick_x, float thumbstick_y)
        {
            this.button_lower = button_lower;
            this.button_upper = button_upper;
            this.trigger_index = trigger_index;
            this.trigger_middle = trigger_middle;
            this.thumbstick_x = thumbstick_x;
            this.thumbstick_y = thumbstick_y;
        }

        public static VRControllerInputMsg Deserialize(MessageDeserializer deserializer) => new VRControllerInputMsg(deserializer);

        private VRControllerInputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.button_lower);
            deserializer.Read(out this.button_upper);
            deserializer.Read(out this.trigger_index);
            deserializer.Read(out this.trigger_middle);
            deserializer.Read(out this.thumbstick_x);
            deserializer.Read(out this.thumbstick_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.button_lower);
            serializer.Write(this.button_upper);
            serializer.Write(this.trigger_index);
            serializer.Write(this.trigger_middle);
            serializer.Write(this.thumbstick_x);
            serializer.Write(this.thumbstick_y);
        }

        public override string ToString()
        {
            return "VRControllerInputMsg: " +
            "\nbutton_lower: " + button_lower.ToString() +
            "\nbutton_upper: " + button_upper.ToString() +
            "\ntrigger_index: " + trigger_index.ToString() +
            "\ntrigger_middle: " + trigger_middle.ToString() +
            "\nthumbstick_x: " + thumbstick_x.ToString() +
            "\nthumbstick_y: " + thumbstick_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
