//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DoosanTeleop
{
    [Serializable]
    public class VRHapticFeedbackMsg : Message
    {
        public const string k_RosMessageName = "doosan_teleop_msgs/VRHapticFeedback";
        public override string RosMessageName => k_RosMessageName;

        //  VRHapticFeedback.msg
        //  Subscribed by the Unity VR app on /vr/right/haptic and /vr/left/haptic
        //  Commands controller vibration
        public float frequency;
        //  Vibration frequency in Hz
        public float amplitude;
        //  Vibration amplitude  (0.0 - 1.0)
        public float seconds;
        //  Duration in seconds  (0.0 = single pulse)

        public VRHapticFeedbackMsg()
        {
            this.frequency = 0.0f;
            this.amplitude = 0.0f;
            this.seconds = 0.0f;
        }

        public VRHapticFeedbackMsg(float frequency, float amplitude, float seconds)
        {
            this.frequency = frequency;
            this.amplitude = amplitude;
            this.seconds = seconds;
        }

        public static VRHapticFeedbackMsg Deserialize(MessageDeserializer deserializer) => new VRHapticFeedbackMsg(deserializer);

        private VRHapticFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.amplitude);
            deserializer.Read(out this.seconds);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frequency);
            serializer.Write(this.amplitude);
            serializer.Write(this.seconds);
        }

        public override string ToString()
        {
            return "VRHapticFeedbackMsg: " +
            "\nfrequency: " + frequency.ToString() +
            "\namplitude: " + amplitude.ToString() +
            "\nseconds: " + seconds.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
